# Generated by Django 4.1.5 on 2023-07-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='active_players_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='free_agents_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='rookies_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='spent_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='use_spent_limit',
            field=models.BooleanField(default=False),
        ),
    ]
