# Generated by Django 4.1.5 on 2023-07-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_date_remove_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_entrees',
            field=models.IntegerField(default=0),
        ),
    ]
