# Generated by Django 4.1.5 on 2023-01-23 21:56

from django.db import migrations, models
import django.db.models.deletion
import main.league.config
import main.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('public_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', main.managers.DiscordAuthorizationManager()),
            ],
        ),
        migrations.CreateModel(
            name='FeatureList',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('features', models.JSONField(default=main.league.config.get_default_features)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryList',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('history', models.JSONField(default=main.league.config.get_default_history)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('height', models.CharField(max_length=6)),
                ('weight', models.CharField(max_length=3)),
                ('primary_position', models.CharField(max_length=1)),
                ('secondary_position', models.CharField(max_length=1)),
                ('attributes', models.JSONField(default=main.league.config.get_default_attributes)),
                ('badges', models.JSONField(default=main.league.config.get_default_badges)),
                ('cash', models.PositiveBigIntegerField(default=1000)),
                ('gems', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('abbrev', models.CharField(max_length=3)),
                ('roster', models.ManyToManyField(related_name='roster', to='main.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='discord_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discorduser'),
        ),
        migrations.AddField(
            model_name='player',
            name='feature_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.featurelist'),
        ),
        migrations.AddField(
            model_name='player',
            name='history_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.historylist'),
        ),
    ]
