# Generated by Django 4.1.5 on 2023-01-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='Player', max_length=16),
        ),
        migrations.AlterField(
            model_name='team',
            name='roster',
            field=models.ManyToManyField(blank=True, related_name='roster', to='main.player'),
        ),
    ]
