# Generated by Django 4.1.5 on 2023-01-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_discorduser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='locale',
            field=models.CharField(max_length=100),
        ),
    ]
