# Generated by Django 4.1.5 on 2023-02-20 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_range1_heightlimit_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contract_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.contract'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.SmallIntegerField(choices=[(70, "5'10"), (71, "5'11"), (72, "6'0"), (73, "6'1"), (74, "6'2"), (75, "6'3"), (76, "6'4"), (77, "6'5"), (78, "6'6"), (79, "6'7"), (80, "6'8"), (81, "6'9"), (82, "6'10"), (83, "6'11"), (84, "7'0"), (85, "7'1"), (86, "7'2"), (87, "7'3")], default=70, max_length=2),
        ),
    ]
