# Generated by Django 4.1.5 on 2023-01-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_player_name_player_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='players',
            field=models.ManyToManyField(related_name='players', to='main.player'),
        ),
    ]
