# Generated by Django 4.1.5 on 2023-01-22 21:29

from django.db import migrations, models
import main.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_discorduser_locale'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', main.managers.DiscordAuthorizationManager()),
            ],
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
