# Generated by Django 4.1.5 on 2023-02-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_player_contract_details_alter_player_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.SmallIntegerField(choices=[(70, "5'10"), (71, "5'11"), (72, "6'0"), (73, "6'1"), (74, "6'2"), (75, "6'3"), (76, "6'4"), (77, "6'5"), (78, "6'6"), (79, "6'7"), (80, "6'8"), (81, "6'9"), (82, "6'10"), (83, "6'11"), (84, "7'0"), (85, "7'1"), (86, "7'2"), (87, "7'3")], default=70),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
