# Generated by Django 4.1.5 on 2023-01-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_discorduser_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='players',
            field=models.ManyToManyField(to='main.player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='roster',
            field=models.ManyToManyField(blank=True, to='main.player'),
        ),
    ]
