# Generated by Django 4.1.5 on 2023-01-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_discorduser_players_alter_team_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='players',
            field=models.ManyToManyField(related_name='players', to='main.player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='roster',
            field=models.ManyToManyField(blank=True, related_name='roster', to='main.player'),
        ),
    ]
