# Generated by Django 4.1.5 on 2023-01-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_discorduser_username_alter_discorduser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permits',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('permits', models.JSONField(default={'fake_permit0': True})),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('height', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=3)),
                ('primary_position', models.CharField(max_length=1)),
                ('secondary_position', models.CharField(max_length=1)),
                ('attributes', models.JSONField(default={'fake_attribute0': 170.0})),
                ('badges', models.JSONField(default={'fake_badge0': 0})),
                ('discord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discorduser')),
                ('permits', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.permits')),
            ],
        ),
    ]
