# Generated by Django 4.1.5 on 2023-01-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_discorduser_players_alter_team_roster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='players',
        ),
        migrations.RemoveField(
            model_name='team',
            name='roster',
        ),
    ]
