# Generated by Django 4.1.5 on 2023-02-21 21:53

from django.db import migrations, models
import django.db.models.deletion
import main.league.config


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_player_contract_details_delete_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown', models.JSONField(blank=True, default=main.league.config.get_default_contract)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='contract_details',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.contract'),
            preserve_default=False,
        ),
    ]
