# Generated by Django 4.1.5 on 2023-01-23 12:15

from django.db import migrations, models
import main.league.config


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_permits_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permits',
            name='permits',
            field=models.JSONField(default=main.league.config.get_default_permits),
        ),
        migrations.AlterField(
            model_name='player',
            name='attributes',
            field=models.JSONField(default=main.league.config.get_default_attributes),
        ),
        migrations.AlterField(
            model_name='player',
            name='badges',
            field=models.JSONField(default=main.league.config.get_default_badges),
        ),
    ]
