# Generated by Django 4.1.5 on 2023-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_permits_featurelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(max_length=6),
        ),
    ]
