# Generated by Django 4.1.5 on 2023-02-22 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_player_current_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height_limits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.heightlimit'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight_limits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.weightlimit'),
        ),
    ]
