# Generated by Django 4.1.5 on 2023-01-29 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_player_height_alter_player_primary_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(170), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
