# Generated by Django 4.1.5 on 2023-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_player_primary_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='player',
            name='primary_position',
            field=models.CharField(max_length=1),
        ),
    ]
