# Generated by Django 4.1.5 on 2023-01-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_player_height_alter_player_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(choices=[('69', "5'9"), ('70', "5'10"), ('71', "5'11"), ('72', "6'0"), ('73', "6'1"), ('74', "6'2"), ('75', "6'3"), ('76', "6'4"), ('77', "6'5"), ('78', "6'6"), ('79', "6'7"), ('80', "6'8"), ('81', "6'9"), ('82', "6'10"), ('83', "6'11"), ('84', "7'0"), ('85', "7'1")], default='69', max_length=2),
        ),
    ]
