# Generated by Django 4.1.5 on 2023-02-25 07:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_player_accepted_offer_player_free_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_length', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('year_one_salary', models.SmallIntegerField(default=0)),
                ('year_two_salary', models.SmallIntegerField(default=0)),
                ('year_three_salary', models.SmallIntegerField(default=0)),
                ('player_option', models.BooleanField(default=False)),
                ('team_option', models.BooleanField(default=False)),
                ('no_trade_clause', models.BooleanField(default=False)),
                ('no_cut_clause', models.BooleanField(default=False)),
                ('player_choice', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='breakdown',
        ),
        migrations.RemoveField(
            model_name='player',
            name='contract_offers',
        ),
        migrations.RemoveField(
            model_name='team',
            name='contract_offers',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_length',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_year',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='contract',
            name='no_cut_clause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='no_trade_clause',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='player_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='team_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='year_one_salary',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='year_three_salary',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='year_two_salary',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PlayerOffers',
        ),
        migrations.DeleteModel(
            name='TeamOffers',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
