# Generated by Django 4.1.5 on 2023-02-07 19:41

from django.db import migrations, models
import django.db.models.deletion
import main.league.config


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_player_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('breakdown', models.JSONField(default=main.league.config.get_default_contract)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.CharField(default='https://cdn.simplystamps.com/media/catalog/product/5/8/5802-n-a-stock-stamp-hcb.png', max_length=100),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('settings', models.JSONField(default=main.league.config.get_default_settings)),
                ('current_season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.season')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='contract_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contract'),
        ),
    ]
