# Generated by Django 4.1.5 on 2023-02-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_offer_remove_contract_breakdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='draft_picks',
        ),
        migrations.RemoveField(
            model_name='team',
            name='trade_logs',
        ),
        migrations.AddField(
            model_name='team',
            name='history_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.historylist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.discorduser'),
            preserve_default=False,
        ),
    ]
