# Generated by Django 4.1.5 on 2023-02-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_player_gems_alter_configuration_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='spent',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
