# Generated by Django 4.1.5 on 2023-02-14 22:15

from django.db import migrations, models
import main.league.config


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_player_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('effected_attributes', models.JSONField(blank=True, default=main.league.config.get_default_physical)),
                ('effected_badges', models.JSONField(blank=True, default=main.league.config.get_default_physical)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
