# Generated by Django 4.1.5 on 2023-02-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_team_history_list_alter_team_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='history_list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.historylist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.discorduser'),
            preserve_default=False,
        ),
    ]
