# Generated by Django 4.1.5 on 2023-02-14 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_physical'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='physical_limits',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.physical'),
        ),
    ]
