# Generated by Django 4.1.5 on 2023-02-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_team_history_list_alter_team_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='feature_list',
        ),
        migrations.DeleteModel(
            name='FeatureList',
        ),
    ]
