# Generated by Django 4.1.5 on 2023-02-14 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_player_physical_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='physical_limits',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.physical'),
        ),
    ]
