# Generated by Django 4.1.5 on 2023-02-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_player_physical_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
