# Generated by Django 4.1.5 on 2023-02-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_player_contract_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='accepted_offer',
        ),
    ]
