# Generated by Django 4.1.5 on 2023-03-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_player_hotzones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
