# Generated by Django 4.1.5 on 2023-03-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heightlimit',
            old_name='height',
            new_name='range1',
        ),
        migrations.AddField(
            model_name='heightlimit',
            name='range2',
            field=models.SmallIntegerField(default=0),
        ),
    ]
