# Generated by Django 4.1.5 on 2023-06-06 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_discorduser_can_update_styles_alter_player_styles'),
        ('stats', '0002_statline_personal_fouls'),
    ]

    operations = [
        migrations.AddField(
            model_name='statline',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stats.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statline',
            name='team_at_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
            preserve_default=False,
        ),
    ]
