# Generated by Django 4.1.5 on 2023-06-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_statline_game_statline_team_at_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
