# Generated by Django 4.1.5 on 2023-06-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
