# Generated by Django 4.1.5 on 2023-06-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_game_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('P', 'Preseason'), ('R', 'Regular Season'), ('P', 'Playoffs'), ('F', 'Finals')], default='R', max_length=1),
        ),
    ]
