# Generated by Django 4.1.5 on 2023-06-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('PRE', 'Preseason'), ('REG', 'Regular Season'), ('PLY', 'Playoffs'), ('FIN', 'Finals')], default='R', max_length=3),
        ),
    ]
