# Generated by Django 4.1.5 on 2023-06-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_rename_seasonaverages_seasonaverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonaverage',
            name='gp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
