# Generated by Django 4.1.5 on 2023-06-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_seasonaverage_gp'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonaverage',
            name='average_type',
            field=models.CharField(choices=[('PRE', 'Preseason'), ('REG', 'Regular Season'), ('PLY', 'Playoffs'), ('FIN', 'Finals')], default='R', max_length=3),
        ),
    ]
