# Generated by Django 4.1.5 on 2023-06-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_rename_seasontotals_seasontotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonaverage',
            name='average_type',
            field=models.CharField(choices=[('PRE', 'Preseason'), ('REG', 'Regular Season'), ('PLY', 'Playoffs'), ('FIN', 'Finals')], default='REG', max_length=3),
        ),
        migrations.AlterField(
            model_name='seasontotal',
            name='total_type',
            field=models.CharField(choices=[('PRE', 'Preseason'), ('REG', 'Regular Season'), ('PLY', 'Playoffs'), ('FIN', 'Finals')], default='REG', max_length=3),
        ),
    ]
