# Generated by Django 4.1.5 on 2023-06-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_alter_seasonaverage_average_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasontotal',
            name='gmsc',
        ),
    ]
