# Generated by Django 4.1.5 on 2023-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_team_show_on_lists'),
        ('stats', '0016_remove_seasontotal_gmsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonaverage',
            name='season',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='seasontotal',
            name='season',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterUniqueTogether(
            name='seasonaverage',
            unique_together={('season', 'team', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='seasontotal',
            unique_together={('season', 'team', 'player')},
        ),
    ]
