# Generated by Django 4.1.5 on 2023-06-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_alter_seasonaverage_season_alter_seasontotal_season_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasonaverage',
            old_name='average_type',
            new_name='game_type',
        ),
        migrations.RenameField(
            model_name='seasontotal',
            old_name='total_type',
            new_name='game_type',
        ),
    ]
