# Generated by Django 4.1.5 on 2023-08-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0020_seasonaverage_manual_entry_seasontotal_manual_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='seasonaverage',
            name='season',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='seasontotal',
            name='season',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='statline',
            name='season',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
