# Wrestling Configuration
# ------------------------------------------------
# By: doublesync
# ------------------------------------------------
# This file contains the configuration for the
# yawn wrestling application.
# ------------------------------------------------

# Settings
# -----------------------------------------------------
# These are the settings for the wrestling application.
# -----------------------------------------------------

max_wrestlers = 1

initial_attributes = {
    # Miscanellous Category
    "In-Ring": 0,
    "Mobility": 0,
    "Toughness": 0,
    # Offense Category
    "Special": 0,
    "Finisher": 0,
    "Arm Power": 0,
    "Leg Power": 0,
    "Grapple Offense": 0,
    "Running Offense": 0,
    "Aerial Offense": 0,
    "Aerial Range": 0,
    "Power Submission Offense": 0,
    "Technical Submission Offense": 0,
    # Durability Category
    "Body Durability": 0,
    "Arm Durability": 0,
    "Leg Durability": 0,
    # Defense Category
    "Strike Reversal": 0,
    "Grapple Reversal": 0,
    "Aerial Reversal": 0,
    "Power Submission Defense": 0,
    "Technical Submission Defense": 0,
    "Pin Escape": 0,
    # Physical Category 
    "Strength": 0,
    "Stamina": 0,
    "Agility": 0,
    "Movement Speed": 0,
    "Recovery": 0,
}
starting_attributes = {
    "Cruiserweight": {
        "Striker": {
            "Arm Power": 60,
            "Leg Power": 60,
            "Grapple Offense": 55,
            "Running Offense": 50,
            "Aerial Offense": 40,
            "Aerial Range": 50,
            "Power Submission Offense": 35,
            "Technical Submission Offense": 40,
            "Strike Reversal": 60,
            "Grapple Reversal": 60,
            "Aerial Reversal": 50,
            "Body Durability": 60,
            "Arm Durability": 65,
            "Leg Durability": 65,
            "Power Submission Defense": 50,
            "Technical Submission Defense": 50,
            "Pin Escape": 55,
            "Strength": 60,
            "Stamina": 60,
            "Agility": 60,
            "Movement Speed": 65,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        },
        "Technician": {
            "Arm Power": 50,
            "Leg Power": 50,
            "Grapple Offense": 65,
            "Running Offense": 50,
            "Aerial Offense": 50,
            "Aerial Range": 50,
            "Power Submission Offense": 30,
            "Technical Submission Offense": 70,
            "Strike Reversal": 50,
            "Grapple Reversal": 55,
            "Aerial Reversal": 50,
            "Body Durability": 55,
            "Arm Durability": 60,
            "Leg Durability": 60,
            "Power Submission Defense": 30,
            "Technical Submission Defense": 70,
            "Pin Escape": 55,
            "Strength": 40,
            "Stamina": 60,
            "Agility": 60,
            "Movement Speed": 70,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        },
        "Powerhouse": {
            "Arm Power": 65,
            "Leg Power": 65,
            "Grapple Offense": 65,
            "Running Offense": 60,
            "Aerial Offense": 30,
            "Aerial Range": 45,
            "Power Submission Offense": 55,
            "Technical Submission Offense": 30,
            "Strike Reversal": 40,
            "Grapple Reversal": 35,
            "Aerial Reversal": 35,
            "Body Durability": 60,
            "Arm Durability": 60,
            "Leg Durability": 60,
            "Power Submission Defense": 50,
            "Technical Submission Defense": 30,
            "Pin Escape": 55,
            "Strength": 70,
            "Stamina": 60,
            "Agility": 50,
            "Movement Speed": 55,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        },
        "High Flyer": {
            "Arm Power": 45,
            "Leg Power": 45,
            "Grapple Offense": 50,
            "Running Offense": 55,
            "Aerial Offense": 70,
            "Aerial Range": 75,
            "Power Submission Offense": 30,
            "Technical Submission Offense": 40,
            "Strike Reversal": 60,
            "Grapple Reversal": 55,
            "Aerial Reversal": 65,
            "Body Durability": 55,
            "Arm Durability": 55,
            "Leg Durability": 55,
            "Power Submission Defense": 60,
            "Technical Submission Defense": 60,
            "Pin Escape": 55,
            "Strength": 55,
            "Stamina": 60,
            "Agility": 75,
            "Movement Speed": 75,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        }
    },
    "Light Heavyweight": {
        "Striker": {
            "Arm Power": 60,
            "Leg Power": 60,
            "Grapple Offense": 55,
            "Running Offense": 50,
            "Aerial Offense": 40,
            "Aerial Range": 70,
            "Power Submission Offense": 35,
            "Technical Submission Offense": 40,
            "Strike Reversal": 60,
            "Grapple Reversal": 60,
            "Aerial Reversal": 50,
            "Body Durability": 60,
            "Arm Durability": 65,
            "Leg Durability": 65,
            "Power Submission Defense": 50,
            "Technical Submission Defense": 50,
            "Pin Escape": 55,
            "Strength": 60,
            "Stamina": 60,
            "Agility": 65,
            "Movement Speed": 65,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        },
        "Technician": {
            "Arm Power": 50,
            "Leg Power": 50,
            "Grapple Offense": 65,
            "Running Offense": 50,
            "Aerial Offense": 50,
            "Aerial Range": 50,
            "Power Submission Offense": 30,
            "Technical Submission Offense": 70,
            "Strike Reversal": 50,
            "Grapple Reversal": 55,
            "Aerial Reversal": 65,
            "Body Durability": 55,
            "Arm Durability": 60,
            "Leg Durability": 60,
            "Power Submission Defense": 30,
            "Technical Submission Defense": 70,
            "Pin Escape": 65,
            "Strength": 40,
            "Stamina": 60,
            "Agility": 60,
            "Movement Speed": 70,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        },
        "Powerhouse": {
            "Arm Power": 65,
            "Leg Power": 65,
            "Grapple Offense": 65,
            "Running Offense": 60,
            "Aerial Offense": 30,
            "Aerial Range": 45,
            "Power Submission Offense": 55,
            "Technical Submission Offense": 30,
            "Strike Reversal": 40,
            "Grapple Reversal": 35,
            "Aerial Reversal": 35,
            "Body Durability": 60,
            "Arm Durability": 60,
            "Leg Durability": 60,
            "Power Submission Defense": 50,
            "Technical Submission Defense": 30,
            "Pin Escape": 55,
            "Strength": 70,
            "Stamina": 60,
            "Agility": 50,
            "Movement Speed": 55,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        },
        "High Flyer": {
            "Arm Power": 45,
            "Leg Power": 45,
            "Grapple Offense": 50,
            "Running Offense": 55,
            "Aerial Offense": 70,
            "Aerial Range": 75,
            "Power Submission Offense": 30,
            "Technical Submission Offense": 40,
            "Strike Reversal": 60,
            "Grapple Reversal": 55,
            "Aerial Reversal": 65,
            "Body Durability": 55,
            "Arm Durability": 55,
            "Leg Durability": 55,
            "Power Submission Defense": 60,
            "Technical Submission Defense": 60,
            "Pin Escape": 55,
            "Strength": 55,
            "Stamina": 60,
            "Agility": 75,
            "Movement Speed": 75,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        }
    },
    "Heavyweight": {
        "Striker": {
            "Arm Power": 60,
            "Leg Power": 60,
            "Grapple Offense": 55,
            "Running Offense": 50,
            "Aerial Offense": 40,
            "Aerial Range": 50,
            "Power Submission Offense": 35,
            "Technical Submission Offense": 40,
            "Strike Reversal": 60,
            "Grapple Reversal": 60,
            "Aerial Reversal": 50,
            "Body Durability": 60,
            "Arm Durability": 65,
            "Leg Durability": 65,
            "Power Submission Defense": 50,
            "Technical Submission Defense": 50,
            "Pin Escape": 55,
            "Strength": 60,
            "Stamina": 60,
            "Agility": 60,
            "Movement Speed": 65,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        },
        "Technician": {
            "Arm Power": 50,
            "Leg Power": 50,
            "Grapple Offense": 65,
            "Running Offense": 50,
            "Aerial Offense": 50,
            "Aerial Range": 50,
            "Power Submission Offense": 30,
            "Technical Submission Offense": 70,
            "Strike Reversal": 52,
            "Grapple Reversal": 55,
            "Aerial Reversal": 65,
            "Body Durability": 55,
            "Arm Durability": 60,
            "Leg Durability": 60,
            "Power Submission Defense": 30,
            "Technical Submission Defense": 70,
            "Pin Escape": 65,
            "Strength": 40,
            "Stamina": 60,
            "Agility": 60,
            "Movement Speed": 70,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        },
        "Powerhouse": {
            "Arm Power": 65,
            "Leg Power": 65,
            "Grapple Offense": 65,
            "Running Offense": 60,
            "Aerial Offense": 30,
            "Aerial Range": 45,
            "Power Submission Offense": 55,
            "Technical Submission Offense": 30,
            "Strike Reversal": 40,
            "Grapple Reversal": 35,
            "Aerial Reversal": 35,
            "Body Durability": 60,
            "Arm Durability": 60,
            "Leg Durability": 60,
            "Power Submission Defense": 50,
            "Technical Submission Defense": 30,
            "Pin Escape": 55,
            "Strength": 70,
            "Stamina": 60,
            "Agility": 50,
            "Movement Speed": 55,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        },
        "High Flyer": {
            "Arm Power": 45,
            "Leg Power": 45,
            "Grapple Offense": 50,
            "Running Offense": 55,
            "Aerial Offense": 70,
            "Aerial Range": 55,
            "Power Submission Offense": 30,
            "Technical Submission Offense": 40,
            "Strike Reversal": 60,
            "Grapple Reversal": 55,
            "Aerial Reversal": 60,
            "Body Durability": 55,
            "Arm Durability": 55,
            "Leg Durability": 55,
            "Power Submission Defense": 60,
            "Technical Submission Defense": 60,
            "Pin Escape": 55,
            "Strength": 55,
            "Stamina": 55,
            "Agility": 55,
            "Movement Speed": 60,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        }
    },
    "Super Heavyweight": {
        "Striker": {
            "Arm Power": 60,
            "Leg Power": 60,
            "Grapple Offense": 55,
            "Running Offense": 50,
            "Aerial Offense": 40,
            "Aerial Range": 50,
            "Power Submission Offense": 35,
            "Technical Submission Offense": 40,
            "Strike Reversal": 60,
            "Grapple Reversal": 60,
            "Aerial Reversal": 50,
            "Body Durability": 60,
            "Arm Durability": 65,
            "Leg Durability": 65,
            "Power Submission Defense": 50,
            "Technical Submission Defense": 50,
            "Pin Escape": 55,
            "Strength": 60,
            "Stamina": 60,
            "Agility": 60,
            "Movement Speed": 65,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        },
        "Technician": {
            "Arm Power": 60,
            "Leg Power": 50,
            "Grapple Offense": 65,
            "Running Offense": 50,
            "Aerial Offense": 50,
            "Aerial Range": 50,
            "Power Submission Offense": 30,
            "Technical Submission Offense": 70,
            "Strike Reversal": 50,
            "Grapple Reversal": 55,
            "Aerial Reversal": 60,
            "Body Durability": 55,
            "Arm Durability": 60,
            "Leg Durability": 60,
            "Power Submission Defense": 30,
            "Technical Submission Defense": 70,
            "Pin Escape": 65,
            "Strength": 50,
            "Stamina": 55,
            "Agility": 55,
            "Movement Speed": 60,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        },
        "Powerhouse": {
            "Arm Power": 65,
            "Leg Power": 65,
            "Grapple Offense": 65,
            "Running Offense": 60,
            "Aerial Offense": 30,
            "Aerial Range": 45,
            "Power Submission Offense": 55,
            "Technical Submission Offense": 30,
            "Strike Reversal": 40,
            "Grapple Reversal": 35,
            "Aerial Reversal": 35,
            "Body Durability": 60,
            "Arm Durability": 60,
            "Leg Durability": 60,
            "Power Submission Defense": 50,
            "Technical Submission Defense": 30,
            "Pin Escape": 55,
            "Strength": 70,
            "Stamina": 60,
            "Agility": 50,
            "Movement Speed": 55,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        },
        "High Flyer": {
            "Arm Power": 45,
            "Leg Power": 45,
            "Grapple Offense": 50,
            "Running Offense": 55,
            "Aerial Offense": 70,
            "Aerial Range": 55,
            "Power Submission Offense": 30,
            "Technical Submission Offense": 40,
            "Strike Reversal": 60,
            "Grapple Reversal": 55,
            "Aerial Reversal": 60,
            "Body Durability": 55,
            "Arm Durability": 55,
            "Leg Durability": 55,
            "Power Submission Defense": 60,
            "Technical Submission Defense": 60,
            "Pin Escape": 55,
            "Strength": 55,
            "Stamina": 55,
            "Agility": 55,
            "Movement Speed": 60,
            "Recovery": 55,
            "Special": 60,
            "Finisher": 60
        }
    }
}
potential_attributes = {
    "Cruiserweight": {
        "Arm Power": 75,
        "Leg Power": 75,
        "Grapple Offense": 65,
        "Running Offense": 85,
        "Aerial Offense": 85,
        "Aerial Range": 85,
        "Power Submission Offense": 55,
        "Technical Submission Offense": 85,
        "Strike Reversal": 75,
        "Grapple Reversal": 75,
        "Aerial Reversal": 85,
        "Body Durability": 65,
        "Arm Durability": 70,
        "Leg Durability": 70,
        "Power Submission Defense": 55,
        "Technical Submission Defense": 85,
        "Pin Escape": 85,
        "Strength": 70,
        "Stamina": 85,
        "Agility": 85,
        "Movement Speed": 85,
        "Recovery": 85,
        "Special": 85,
        "Finisher": 85
    },
    "Light Heavyweight": {
        "Arm Power": 75,
        "Leg Power": 75,
        "Grapple Offense": 70,
        "Running Offense": 80,
        "Aerial Offense": 80,
        "Aerial Range": 75,
        "Power Submission Offense": 65,
        "Technical Submission Offense": 75,
        "Strike Reversal": 85,
        "Grapple Reversal": 85,
        "Aerial Reversal": 75,
        "Body Durability": 75,
        "Arm Durability": 75,
        "Leg Durability": 75,
        "Power Submission Defense": 65,
        "Technical Submission Defense": 75,
        "Pin Escape": 85,
        "Strength": 75,
        "Stamina": 75,
        "Agility": 75,
        "Movement Speed": 75,
        "Recovery": 80,
        "Special": 85,
        "Finisher": 85
    },
    "Heavyweight": {
        "Arm Power": 80,
        "Leg Power": 80,
        "Grapple Offense": 80,
        "Running Offense": 75,
        "Aerial Offense": 75,
        "Aerial Range": 70,
        "Power Submission Offense": 75,
        "Technical Submission Offense": 65,
        "Strike Reversal": 70,
        "Grapple Reversal": 70,
        "Aerial Reversal": 65,
        "Body Durability": 80,
        "Arm Durability": 80,
        "Leg Durability": 85,
        "Power Submission Defense": 75,
        "Technical Submission Defense": 65,
        "Pin Escape": 85,
        "Strength": 80,
        "Stamina": 65,
        "Agility": 65,
        "Movement Speed": 70,
        "Recovery": 75,
        "Special": 85,
        "Finisher": 85
    },
    "Super Heavyweight": {
        "Arm Power": 85,
        "Leg Power": 85,
        "Grapple Offense": 85,
        "Running Offense": 65,
        "Aerial Offense": 65,
        "Aerial Range": 50,
        "Power Submission Offense": 85,
        "Technical Submission Offense": 55,
        "Strike Reversal": 55,
        "Grapple Reversal": 65,
        "Aerial Reversal": 55,
        "Body Durability": 85,
        "Arm Durability": 85,
        "Leg Durability": 65,
        "Power Submission Defense": 85,
        "Technical Submission Defense": 55,
        "Pin Escape": 85,
        "Strength": 85,
        "Stamina": 50,
        "Agility": 50,
        "Movement Speed": 55,
        "Recovery": 65,
        "Special": 85,
        "Finisher": 85
    }
}

#  Wrestling Validations
# --------------------------------------------------------
# These are the validations for the wrestling application.
# --------------------------------------------------------


#  Wrestling Tests
# ----------------------------------------------
# These are tests for the wrestling application.
# ----------------------------------------------

# --------------------------------------------------------------------------
# These tests makes sure that the starting / potential attributes are valid.
# --------------------------------------------------------------------------

# for _, weight in starting_attributes.items():
#     for _, type in weight.items():
#         for k, attribute in type.items():
#             if not k in initial_attributes:
#                 print(f"Invalid attribute: {k} not in starting attributes.")

# for _, weight in potential_attributes.items():
#     for k, attribute in weight.items():
#         if not k in initial_attributes:
#             print(f"Invalid attribute: {k} not in potential attributes.")