# Generated by Django 4.1.5 on 2023-02-20 21:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.league.config
import main.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('breakdown', models.JSONField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('discord_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('public_flags', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('locale', models.CharField(max_length=100)),
                ('mfa_enabled', models.BooleanField()),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', main.managers.DiscordAuthorizationManager()),
            ],
        ),
        migrations.CreateModel(
            name='FeatureList',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('features', models.JSONField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='HeightLimit',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('range1', models.SmallIntegerField(default=0)),
                ('range2', models.SmallIntegerField(default=0)),
                ('limits', models.JSONField(default=main.league.config.get_default_limits)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryList',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('history', models.JSONField(blank=True, default=main.league.config.get_default_history)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerOffers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offers', models.JSONField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamOffers',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offers', models.JSONField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='WeightLimit',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('range1', models.SmallIntegerField(default=0)),
                ('range2', models.SmallIntegerField(default=0)),
                ('limits', models.JSONField(default=main.league.config.get_default_limits)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('logo', models.CharField(default='https://cdn.simplystamps.com/media/catalog/product/5/8/5802-n-a-stock-stamp-hcb.png', max_length=100)),
                ('abbrev', models.CharField(max_length=3)),
                ('trade_logs', models.JSONField(blank=True, default=None)),
                ('draft_picks', models.JSONField(blank=True, default=None)),
                ('contract_offers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.teamoffers')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='Unknown', max_length=16)),
                ('last_name', models.CharField(default='Player', max_length=16)),
                ('height', models.CharField(choices=[(69, "5'9"), (70, "5'10"), (71, "5'11"), (72, "6'0"), (73, "6'1"), (74, "6'2"), (75, "6'3"), (76, "6'4"), (77, "6'5"), (78, "6'6"), (79, "6'7"), (80, "6'8"), (81, "6'9"), (82, "6'10"), (83, "6'11"), (84, "7'0"), (85, "7'1"), (86, "7'2"), (87, "7'3")], default=69, max_length=2)),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(170), django.core.validators.MaxValueValidator(300)])),
                ('primary_position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], default='PG', max_length=2)),
                ('secondary_position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], default='PG', max_length=2)),
                ('jersey_number', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('attributes', models.JSONField(default=main.league.config.get_default_attributes)),
                ('badges', models.JSONField(default=main.league.config.get_default_badges)),
                ('cash', models.PositiveBigIntegerField(default=1000)),
                ('spent', models.PositiveBigIntegerField(default=0)),
                ('upgrades_pending', models.BooleanField(default=False)),
                ('contract_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contract')),
                ('contract_offers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.playeroffers')),
                ('current_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
                ('discord_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discorduser')),
                ('feature_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.featurelist')),
                ('height_limits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.heightlimit')),
                ('history_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.historylist')),
                ('weight_limits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weightlimit')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('settings', models.JSONField(blank=True, default=main.league.config.get_default_settings)),
                ('current_season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.season')),
            ],
        ),
    ]
