# Generated by Django 4.1.5 on 2023-02-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heightlimit',
            old_name='range1',
            new_name='height',
        ),
        migrations.RemoveField(
            model_name='heightlimit',
            name='range2',
        ),
    ]
