# Generated by Django 4.1.5 on 2023-02-22 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_player_contract_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
