# Generated by Django 4.1.5 on 2023-02-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_team_draft_picks_remove_team_trade_logs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='history_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.historylist'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.discorduser'),
        ),
    ]
