# Generated by Django 4.1.5 on 2023-02-25 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_player_feature_list_delete_featurelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contract_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contract'),
        ),
    ]
