# Generated by Django 4.1.5 on 2023-03-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_player_years_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='contract_details',
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
