# Generated by Django 4.1.5 on 2023-03-09 22:35

from django.db import migrations, models
import main.league.config


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_contract_contract_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hotzones',
            field=models.JSONField(default=main.league.config.get_default_hotzones),
        ),
    ]
