# Generated by Django 4.1.5 on 2023-03-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_height_heightlimit_range1_heightlimit_range2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='height_limits',
        ),
        migrations.RemoveField(
            model_name='player',
            name='weight_limits',
        ),
        migrations.DeleteModel(
            name='HeightLimit',
        ),
        migrations.DeleteModel(
            name='WeightLimit',
        ),
    ]
