# Generated by Django 4.1.5 on 2023-03-11 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_player_height_limits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='primary_archetype',
            field=models.CharField(choices=[('Shooter', 'Shooter'), ('Slasher', 'Slasher'), ('Playmaker', 'Playmaker'), ('Post Scorer', 'Post Scorer'), ('Rebounder', 'Rebounder'), ('Perimeter Defender', 'Perimeter Defender'), ('Interior Defender', 'Interior Defender'), ('All Rounder', 'All Rounder')], default='Shooter', max_length=36),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_archetype',
            field=models.CharField(choices=[('Shooter', 'Shooter'), ('Slasher', 'Slasher'), ('Playmaker', 'Playmaker'), ('Post Scorer', 'Post Scorer'), ('Rebounder', 'Rebounder'), ('Perimeter Defender', 'Perimeter Defender'), ('Interior Defender', 'Interior Defender'), ('All Rounder', 'All Rounder')], default='Shooter', max_length=36),
        ),
        migrations.AddField(
            model_name='player',
            name='trait_one',
            field=models.CharField(choices=[('Movement Shooter', 'Movement Shooter'), ('3PT Shooter', '3PT Shooter'), ('Midrange Menace', 'Midrange Menace'), ('Finesse Finisher', 'Finesse Finisher'), ('Fierce Finisher', 'Fierce Finisher'), ('Ankle Snatcher', 'Ankle Snatcher'), ('Passing Maestro', 'Passing Maestro'), ('Rebound Hound', 'Rebound Hound'), ('Interior Anchor', 'Interior Anchor'), ('Perimeter Lockdown', 'Perimeter Lockdown'), ('Post-Up Powerhouse', 'Post-Up Powerhouse'), ('Dribble Driver', 'Dribble Driver'), ('Post-Up Conductor', 'Post-Up Conductor')], default='Movement Shooter', max_length=36),
        ),
        migrations.AddField(
            model_name='player',
            name='trait_three',
            field=models.CharField(choices=[('Movement Shooter', 'Movement Shooter'), ('3PT Shooter', '3PT Shooter'), ('Midrange Menace', 'Midrange Menace'), ('Finesse Finisher', 'Finesse Finisher'), ('Fierce Finisher', 'Fierce Finisher'), ('Ankle Snatcher', 'Ankle Snatcher'), ('Passing Maestro', 'Passing Maestro'), ('Rebound Hound', 'Rebound Hound'), ('Interior Anchor', 'Interior Anchor'), ('Perimeter Lockdown', 'Perimeter Lockdown'), ('Post-Up Powerhouse', 'Post-Up Powerhouse'), ('Dribble Driver', 'Dribble Driver'), ('Post-Up Conductor', 'Post-Up Conductor')], default='Movement Shooter', max_length=36),
        ),
        migrations.AddField(
            model_name='player',
            name='trait_two',
            field=models.CharField(choices=[('Movement Shooter', 'Movement Shooter'), ('3PT Shooter', '3PT Shooter'), ('Midrange Menace', 'Midrange Menace'), ('Finesse Finisher', 'Finesse Finisher'), ('Fierce Finisher', 'Fierce Finisher'), ('Ankle Snatcher', 'Ankle Snatcher'), ('Passing Maestro', 'Passing Maestro'), ('Rebound Hound', 'Rebound Hound'), ('Interior Anchor', 'Interior Anchor'), ('Perimeter Lockdown', 'Perimeter Lockdown'), ('Post-Up Powerhouse', 'Post-Up Powerhouse'), ('Dribble Driver', 'Dribble Driver'), ('Post-Up Conductor', 'Post-Up Conductor')], default='Movement Shooter', max_length=36),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.SmallIntegerField(choices=[(72, "6'0"), (73, "6'1"), (74, "6'2"), (75, "6'3"), (76, "6'4"), (77, "6'5"), (78, "6'6"), (79, "6'7"), (80, "6'8"), (81, "6'9"), (82, "6'10"), (83, "6'11"), (84, "7'0")], default=72),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(270)]),
        ),
    ]
