# Generated by Django 4.1.5 on 2023-03-14 12:37

from django.db import migrations, models
import main.league.config


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_player_salary_alter_player_primary_archetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='picks',
            field=models.JSONField(default=main.league.config.get_default_picks),
        ),
    ]
