# Generated by Django 4.1.5 on 2023-03-15 02:11

from django.db import migrations, models
import main.league.config


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_player_trait_three_player_cyberface'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tendencies',
            field=models.JSONField(default=main.league.config.get_default_tendencies),
        ),
    ]
