# Generated by Django 4.1.5 on 2023-03-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_player_tendencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='can_update_players',
            field=models.BooleanField(default=False),
        ),
    ]
