# Generated by Django 4.1.5 on 2023-03-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_discorduser_can_update_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='last_reward',
            field=models.DateTimeField(null=True),
        ),
    ]
