# Generated by Django 4.1.5 on 2023-04-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_discorduser_last_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('amount', models.PositiveBigIntegerField()),
                ('one_use', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
