# Generated by Django 4.1.5 on 2023-04-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_player_statics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('cash_taken', 'Cash Taken'), ('cash_given', 'Cash Given')], default='cash_taken', max_length=16)),
                ('amount', models.PositiveBigIntegerField()),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discorduser')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
    ]
