# Generated by Django 4.1.5 on 2023-04-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(default='Default Coupon', max_length=16),
        ),
    ]
