# Generated by Django 4.1.5 on 2023-04-11 18:00

from django.db import migrations, models
import django.db.models.deletion
import main.league.config


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_coupon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.JSONField(default=main.league.config.get_default_trade_offer)),
                ('accepted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='main.team')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main.team')),
            ],
        ),
    ]
