# Generated by Django 4.1.5 on 2023-04-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_tradeoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
