# Generated by Django 4.1.5 on 2023-04-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_discorduser_can_approve_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
