# Generated by Django 4.1.5 on 2023-04-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(default='Content', max_length=100),
        ),
    ]
