# Generated by Django 4.1.5 on 2023-04-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_notification_title_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='plays_in_main_league',
            field=models.BooleanField(default=True),
        ),
    ]
