# Generated by Django 4.1.5 on 2023-04-14 03:08

from django.db import migrations, models
import main.league.config


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_team_plays_in_main_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='picks',
            field=models.JSONField(blank=True, default=main.league.config.get_default_picks, null=True),
        ),
    ]
