# Generated by Django 4.1.5 on 2023-04-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_team_picks'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contract_benefits',
            field=models.CharField(choices=[('N/A', 'N/A'), ('No Trade Clause', 'No Trade Clause'), ('No Cut Clause', 'No Cut Clause'), ('No Trade Clause + No Cut Clause', 'No Trade Clause + No Cut Clause')], default='N/A', max_length=54),
        ),
        migrations.AddField(
            model_name='player',
            name='contract_ends_after',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='contract_option',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Team Option', 'Team Option'), ('Player Option', 'Player Option')], default='N/A', max_length=54),
        ),
    ]
