# Generated by Django 4.1.5 on 2023-04-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_player_cash_alter_player_contract_benefits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MVP', 'MVP'), ('DPOY', 'DPOY'), ('MIP', 'MIP'), ('ROY', 'ROY'), ('6MOY', '6MOY'), ('AH1ST', 'AH1ST'), ('AH2ND', 'AH2ND'), ('D1ST', 'D1ST'), ('D2ND', 'D2ND'), ('KOTS', 'KOTS')], default='MVP', max_length=32)),
                ('description', models.CharField(default='Description', max_length=32)),
                ('season', models.PositiveSmallIntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
            ],
        ),
    ]
