# Generated by Django 4.1.5 on 2023-05-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_player_headshot_alter_award_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(choices=[('MVP', 'MVP'), ('DPOY', 'DPOY'), ('MIP', 'MIP'), ('ROY', 'ROY'), ('6MOY', '6MOY'), ('AH1ST', 'AH1ST'), ('AH2ND', 'AH2ND'), ('D1ST', 'D1ST'), ('D2ND', 'D2ND'), ('KOTS', 'KOTS'), ('RING', 'RING'), ('FMVP', 'FMVP'), ('ASG', 'ASG'), ('ASGMVP', 'ASGMVP')], default='MVP', max_length=6),
        ),
    ]
