# Generated by Django 4.1.5 on 2023-05-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_award_name_alter_player_discord_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='player_slots',
            field=models.SmallIntegerField(default=1),
        ),
    ]
