# Generated by Django 4.1.5 on 2023-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_contractoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoffer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
