# Generated by Django 4.1.5 on 2023-05-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_contractoffer_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractoffer',
            name='notes',
            field=models.CharField(blank=True, default='No notes.', max_length=100, null=True),
        ),
    ]
