# Generated by Django 4.1.5 on 2023-05-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_contractoffer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contract_notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
