# Generated by Django 4.1.5 on 2023-05-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_player_contract_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_rookie',
            field=models.BooleanField(default=False),
        ),
    ]
