# Generated by Django 4.1.5 on 2023-06-03 15:45

from django.db import migrations, models
import main.league.config


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_player_is_rookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='styles',
            field=models.JSONField(default=main.league.config.get_default_styles),
        ),
    ]
