# Generated by Django 4.1.5 on 2023-06-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_player_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='can_change_styles',
            field=models.BooleanField(default=False),
        ),
    ]
