# Generated by Django 4.1.5 on 2023-06-04 23:52

from django.db import migrations, models
import main.league.config


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_discorduser_can_change_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='can_update_styles',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='styles',
            field=models.JSONField(blank=True, default=main.league.config.get_default_styles),
        ),
    ]
