# Generated by Django 4.1.5 on 2023-06-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_discorduser_can_update_styles_alter_player_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='show_on_lists',
            field=models.BooleanField(default=True),
        ),
    ]
