# Generated by Django 4.1.5 on 2023-07-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_player_trait_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cap_hit',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
