# Generated by Django 4.1.5 on 2023-07-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_player_cap_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='can_edit_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='can_edit_scores',
            field=models.BooleanField(default=False),
        ),
    ]
