# Generated by Django 4.1.5 on 2023-07-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_discorduser_can_edit_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='primary_archetype',
        ),
        migrations.RemoveField(
            model_name='player',
            name='secondary_archetype',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trait_one',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trait_three',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trait_two',
        ),
        migrations.AddField(
            model_name='player',
            name='primary_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='primary_badges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_badges',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
