# Generated by Django 4.1.5 on 2023-07-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_remove_player_primary_archetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='player_slots',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='contract_ends_after',
            field=models.SmallIntegerField(default=999),
        ),
    ]
