# Generated by Django 4.1.5 on 2023-07-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_alter_discorduser_player_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='player_slots',
            field=models.SmallIntegerField(default=1),
        ),
    ]
