# Generated by Django 4.1.5 on 2023-08-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_alter_discorduser_player_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='badge_upgrades_given',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
