# Generated by Django 4.1.5 on 2023-07-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='answers',
            field=models.CharField(default='Yes, No', max_length=200),
        ),
    ]
