# Generated by Django 4.1.5 on 2023-07-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
