# Generated by Django 4.1.5 on 2023-08-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0072_player_badge_upgrades_given'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wrestler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100)),
                ('twitch_handle', models.CharField(max_length=100)),
                ('disposition', models.SmallIntegerField()),
                ('division', models.CharField(max_length=100)),
                ('gimmick', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('worker_disposition', models.CharField(max_length=100)),
                ('worker_perception', models.SmallIntegerField()),
                ('size', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('overall', models.SmallIntegerField(default=0)),
                ('accolades', models.TextField(blank=True, null=True)),
                ('total_xp', models.SmallIntegerField()),
                ('attributes', models.JSONField()),
                ('profession', models.CharField(max_length=100)),
                ('wrestler_class', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('entrance', models.CharField(max_length=100)),
                ('victory', models.CharField(max_length=100)),
                ('music', models.CharField(max_length=100)),
                ('render', models.CharField(max_length=100)),
                ('story', models.TextField(blank=True, null=True)),
                ('move_set', models.CharField(max_length=100)),
                ('finishing_move_1', models.CharField(max_length=100)),
                ('finishing_move_2', models.CharField(max_length=100)),
                ('signature_move_1', models.CharField(max_length=100)),
                ('signature_move_2', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('first_show', models.SmallIntegerField(blank=True, null=True)),
                ('booking_rate', models.SmallIntegerField(blank=True, null=True)),
                ('one_on_one_matches', models.SmallIntegerField(blank=True, null=True)),
                ('two_on_two_matches', models.SmallIntegerField(blank=True, null=True)),
                ('special_matches', models.SmallIntegerField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discorduser')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrestling.team')),
            ],
        ),
    ]
