# Generated by Django 4.1.5 on 2023-08-31 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrestling', '0003_title_reign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrestling.team'),
        ),
    ]
