# Generated by Django 4.1.5 on 2023-09-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrestling', '0004_alter_wrestler_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wrestler',
            old_name='render',
            new_name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='wrestler',
            name='booking_rate',
        ),
        migrations.RemoveField(
            model_name='wrestler',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='wrestler',
            name='one_on_one_matches',
        ),
        migrations.RemoveField(
            model_name='wrestler',
            name='special_matches',
        ),
        migrations.RemoveField(
            model_name='wrestler',
            name='two_on_two_matches',
        ),
        migrations.RemoveField(
            model_name='wrestler',
            name='worker_perception',
        ),
        migrations.AddField(
            model_name='wrestler',
            name='payback_one_picture',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wrestler',
            name='payback_two_picture',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
